config/routes.rb
Rails.application.routes.draw do

    root 'pages#index'
    get 'about', to: 'pages#about'
    get 'signup', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :articles
    resources :users, except: [:new]
    resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 3, maximum: 1000 }
    validates :user_id, presence: true
    validates :category_id, presence: true
    belongs_to :user
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :articles
    validates :name, presence: true, uniqueness: { case_sensitive: true }, length: { minimum: 1, maximum: 25 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    before_save { self.email = email.downcase }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def new
        @article = Article.new
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def create
        if require_user
            return
        end
        @article = Article.new(article_params)
        @article.user = current_user
        @article.category_id = params[:article][:category_id]
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if current_user != @article.user
            flash[:danger] = "You may not edit this article"
            redirect_back(fallback_location: root_path)
            return
        end
        if @article.update(article_params)
            flash[:success] = "Article was updated"
            redirect_to article_path(@article)
        else
            flash[:notice] = "Article was not updated"
            render 'edit'
        end
    end

    def destroy
        if current_user != @article.user
            flash[:danger] = "You may not delete this article"
            redirect_back(fallback_location: root_path)
            return
        end
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :description)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
    end

    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user  && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have logged in"
            redirect_to users_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the alpha blog #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-6">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-6">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :category %>
                </div>
                <div class="col-sm-6">
                    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "btn btn-secondary dropdown-toggle text-light"}) %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: 'btn btn-primary btn-large' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= render 'shared/article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<h4 align="center">Category: <%= @article.category.name %></h4>

<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
        <ul class="listing">
            <div class="row" align="center">
                <div class="col-md-4 col-md-offset-4">
                    <li>
                        <%= link_to image_tag("https://imgur.com/7XYwWuy.png", alt: @article.user.username), user_path(@article.user) %>
                    </li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li>
                        <small>
                            <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                        </small>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= @article.description %>
</div>

<div class="btn-group-fab" role="group" aria-label="FAB Menu">
    <% if current_user == @article.user %>
        <%= button_to edit_article_path(@article), class: "btn btn-main btn-primary has-tooltip btn-first", method: :get do %>
            <i class="fa fa-pencil"></i>
        <% end %>
        <%= button_to article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-main btn-primary btn-second btn-primary has-tooltip", method: :get do %>
            <i class="fa fa-trash"></i>
        <% end %>
    <% end %>
</div>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
<div align="center">
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li class="article-title">
                        <%= link_to category.name, category_path(category) %>
                    </li>
                    <li>
                        <small>
                            <%= pluralize(category.articles.count, "article") if category.articles %>
                        </small>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %> articles</h1>
<%= render 'shared/article', obj: @category.articles %>
<div align="center">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to "dashblog", root_path, class: "navbar-brand", id: "logo" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to "Articles", articles_path %>
                </li>
                <li>
                    <%= link_to "Members", users_path %>
                </li>
                <li>
                    <%= link_to "Categories", categories_path %>
                </li>
                <li>
                    <%= link_to "Create Article", new_article_path if logged_in? %>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <li>
                        <%= link_to current_user.username, user_path(current_user) %>
                    </li>
                    <li>
                        <%= link_to "Sign out", logout_path, method: :delete %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Sign in", login_path %>
                    </li>
                    <li>
                        <%= link_to "Sign up", signup_path %>
                    </li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>dashblog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'layouts/navigation' %>
        <%= render 'shared/messages' %>
        <%= yield %>
    </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <h1>About Blog</h1>
    <img src="https://media1.tenor.com/images/cc63a036b412db9d0c0c5259174ac0c7/tenor.gif" alt="Eevee dance" class="img-thumbnail">
    <p><br>Dashblog is created by <a hred="https://t.me/OlexiyUA">dashbug</p> 
</div>

app/views/pages/index.html.erb
<div class="container">
    <h1>Welcome to dashblog,
        <%=
            if logged_in?
                current_user.username
            else
                "Anonymous"
            end
        %>
    </h1>
    <% if logged_in? %>
        <br>
        <%= button_to 'Sign out', logout_path, class: "btn btn-lg btn-outline-secondary", method: :delete %>
    <% else %>
        <br>
        <%= button_to 'Sign in', login_path, class: "btn btn-lg btn-outline-secondary", method: :get %>
        <br>
        <%= button_to 'Sign up', signup_path, class: "btn btn-lg btn-outline-secondary", method: :get %>
        <br><br>
    <% end %>
    <br>
    <%= button_to 'Articles', articles_path, class: "btn btn-lg btn-outline-secondary", method: :get %>
    <br>
    <%= button_to 'Members', users_path, class: "btn btn-lg btn-outline-secondary", method: :get %>
    <br>
    <%= button_to 'About', about_path, class: "btn btn-lg btn-outline-secondary", method: :get %>
</div>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                    <%= article.description %>
                    <div class="article-meta-details">
                        <small>
                            Created by:
                            <%=
                                if article.user
                                    link_to article.user.username, user_path(article.user)
                                end
                            %>
                            , Category:
                            <%=
                                if article.category
                                    link_to article.category.name, category_path(article.category)
                                end
                            %>,
                            <%= time_ago_in_words(article.created_at) %> ago,
                            last updated: <%= time_ago_in_words(article.updated_at) %> ago
                        </small>
                    </div>
                </div>
                <div class="article-actions">
                    <% if current_user == article.user %>
                        <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                        <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<div class="btn-group-fab" role="group" aria-label="FAB Menu">
    <% if logged_in?%>
        <%= button_to new_article_path, class: "btn btn-main btn-primary has-tooltip btn-first", method: :get do %>
            <i class="fa fa-plus"></i>
        <% end %>
    <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg|%>
                                <li>
                                    <%= msg %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
            <% end %>
        </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-2">
            [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li>
                        <%= link_to image_tag("https://imgur.com/7XYwWuy.png", alt: user.username), user_path(user) %>
                    </li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li>
                        <small>
                            <%= pluralize(user.articles.count, "article") if user.articles %>
                        </small>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row" align="center">
    <div class="col-md-4 col-md-offset-4 center">
        <%= image_tag("https://imgur.com/7XYwWuy.png", alt: @user.username) %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render 'shared/article', obj: @user.articles %>
<div align="center">
    <%= will_paginate @user_articles %>
</div>